apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test
on:
  workflow_dispatch:
jobs:
  caller:
    uses: ldorg/manual-test/manual-test-wf.yml
    with:
      instructions: "Simon says..."
      assignee: ""
